# Generated by Django 4.2.2 on 2023-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_rename_categories_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
