# Generated by Django 4.2.2 on 2023-06-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_commentunderpost_dislikes_commentunderpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
